dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - integration/rocket-chat/node_modules

services:
  - mongodb

jdk:
  - openjdk8

install:
  - mvn -B clean install -Dquick

script:
  - mvn -B -DargLine="-Xmx2g" test
