dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - frontend/src/bower_components
  - frontend/src/node_modules
  - integration/rocket-chat/node_modules

services:
  - mongodb

jdk:
  - openjdk8

before_install:
  - gem install sass
  - gem install compass

install:
  - mvn -B clean install -Dquick

script:
  - mvn -B -DargLine="-Xmx2g" test

jobs:
  include:
    - stage: test
    - stage: documentation
      if: branch IN (master, documentation) AND type IN (push, api)
      script: true
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/target/html/
        github_token: ${GH_TOKEN}
    - stage: release
      if: tag =~ ^smarti- AND type = push
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y rpm
      script: mvn -B -f dist/ package -Pdeb,rpm
      deploy:
        provider: releases
        api_key: ${GH_TOKEN}
        file_glob: true
        file:
          - application/target/*-exec.jar
          - dist/target/*.deb
          - dist/target/rpm/smarti/RPMS/noarch/*.rpm
        skip_cleanup: true
        name: ${TRAVIS_TAG}
        tag_name: ${TRAVIS_TAG}
        target_commitish: ${TRAVIS_COMMIT}
        draft: true
        on:
          tags: true
