image: redlinkgmbh/base-dev

pipelines:
  default:
    - step:
        script:
          - mkdir -p /data/mongo-db && mongod --dbpath=/data/mongo-db --fork --logpath /data/mongod.log
          - git remote rename origin upstream
          - mvn -q -B -s .ci/settings.xml clean install || { git diff && exit 1; }
          - git remote rename upstream origin
          - ./.ci/uploadArtifacts.sh
  branches:
    master:
      - step:
          script:
            - mkdir -p /data/mongo-db && mongod --dbpath=/data/mongo-db --fork --logpath /data/mongod.log
            - git remote rename origin upstream
            - mvn -q -B -s .ci/settings.xml clean install
            - mvn -q -B -s .ci/settings.xml package -Dquick -Pdeb,rpm -rf :smarti-dist
            - git remote rename upstream origin
            - ./.ci/uploadArtifacts.sh
  tags:
    smarti-*:
      - step:
          script:
            - mkdir -p /data/mongo-db && mongod --dbpath=/data/mongo-db --fork --logpath /data/mongod.log
            - git remote rename origin upstream
            - mvn -q -B -s .ci/settings.xml clean install
            - mvn -q -B -s .ci/settings.xml package -Dquick -Pdeb,rpm -rf :smarti-dist
            - git remote rename upstream origin
            - ./.ci/uploadArtifacts.sh --release --checksums
